# Generated by Django 3.0.2 on 2020-03-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='passwd',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='rpasswd',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
