# Generated by Django 3.0.2 on 2020-03-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20200307_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdata',
        ),
    ]
