# Generated by Django 3.0.2 on 2020-03-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donerinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('cuntry', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('bloodgrp', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Doner',
        ),
        migrations.AddField(
            model_name='bloodbankinfo',
            name='img',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
