# Generated by Django 3.0.2 on 2020-03-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbankinfo',
            name='img',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doner',
            name='img',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
