# Generated by Django 3.0.2 on 2020-03-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doner', '0002_auto_20200311_2251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donerinfo',
            new_name='Doner',
        ),
    ]
