# Generated by Django 3.0.2 on 2020-03-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doner', '0002_auto_20200309_0155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doner',
            new_name='Donerinfo',
        ),
    ]
