# Generated by Django 3.0.2 on 2020-03-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doner', '0003_auto_20200311_2254'),
        ('Doner', '0003_auto_20200311_2237'),
    ]

    operations = [
    ]
