# Generated by Django 3.0.2 on 2020-03-11 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doner', '0005_auto_20200312_0007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReqDoner',
            new_name='ReqDonerinfo',
        ),
    ]
