# Generated by Django 3.0.2 on 2020-03-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doner', '0006_auto_20200312_0038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodBankinfo',
        ),
        migrations.DeleteModel(
            name='ReqDonerinfo',
        ),
    ]
