# Generated by Django 3.0.2 on 2020-03-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doner', '0007_auto_20200312_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqDonerinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('doctor_name', models.CharField(max_length=20)),
                ('bloodgrp', models.CharField(max_length=10)),
                ('cuntry', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('hospital_address', models.TextField()),
                ('c_name', models.CharField(max_length=20)),
                ('c_mobile', models.CharField(max_length=10)),
                ('c_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
