# Generated by Django 3.0.2 on 2020-03-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doner', '0008_reqdonerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBankinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('bb_name', models.CharField(max_length=20)),
                ('cuntry', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('bb_address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('bb_mobile', models.CharField(max_length=10)),
                ('bb_email', models.EmailField(max_length=254)),
                ('about', models.TextField()),
            ],
        ),
    ]
