# Generated by Django 3.0.2 on 2020-03-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doner', '0013_remove_hospital_bloodgrp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbankinfo',
            old_name='bb_name',
            new_name='name',
        ),
    ]
