# Generated by Django 3.0.2 on 2020-03-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doner', '0015_auto_20200327_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donerinfo',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
